version: "3.9"

services:
  db:
    image: postgres:16
    container_name: lovnity-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lovnity
    ports:
      - "5432:5432"
    volumes:
      - lovnity_data:/var/lib/postgresql/data

volumes:
  lovnity_data: